version: 0.2

phases:
  install:
    commands:
      - echo installing Node and npm ...
      - curl -sL https://deb.nodesource.com/setup_10.x | bash -
      - apt-get install -y nodejs

  pre_build:
    commands:
      - echo installing dependencies ...
      - npm install
      # - npm update

  build:
    commands:
      - echo building ...
      - npm run build

  post_build:
    commands:
      - echo clearing old bucket content ...
      - aws s3 rm s3://kevhunte/ --recursive #site bucket

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist