version: 0.2

phases:
  install:
    commands:
      - echo installing Node and npm ...
      - curl -sL https://deb.nodesource.com/setup_10.x | bash -
      - apt install -y nodejs

  pre_build:
    commands:
      - echo installing dependencies ...
      - npm install

  build:
    commands:
      - echo clearing old bucket content ...
      - aws s3 rm --recursive s3://kevhunte
      - echo building ...
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist