name: Publish to GitHub Pages
on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  publish:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup node
        run: npm install

      - name: Generate site
        run: npm run build

      - name: Configure Single Page Application routing
        run: cp dist/index.html dist/404.html 

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist